---
kind: pipeline
type: docker
name: argos-collector-build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: argosnotary/argos-build:3.6.3
  commands:
  - mvn versions:set -DnewVersion=${DRONE_TAG:-${DRONE_BRANCH//\//_}} -DgenerateBackupPoms=false -DprocessAllModules
  - mvn -q install -DskipTests
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository

- name: pitest
  image: argosnotary/argos-build:3.6.3
  commands:
  - mvn verify -Ppitest
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  depends_on:
  - build

- name: sonar
  image: argosnotary/argos-build:3.6.3
  commands:
  - mvn -q -e verify sonar:sonar -Psonar -Dsonar.projectKey=argosnotary_argos-parent -Dsonar.organization=argosnotary -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
  environment:
    SONAR_LOGIN:
      from_secret: sonar_login
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  when:
    event:
    - tag
    - push
  depends_on:
  - pitest

- name: argos-xldeploy-collector-service
  image: argosnotary/argos-docker-base:11.0.8
  detach: true
  environment:
    argos-collector.baseurl: http://argos-collector-xl-deploy-stub:8080
    spring.profiles.active: XLDEPLOY
    RUNNABLE_JAR: '/drone/src/argos-collector-service/target/argos-collector-service.jar'
  depends_on:
  - pitest
  - sonar

- name: argos-git-collector-service
  image: argosnotary/argos-docker-base:11.0.8
  detach: true
  environment:
    argos-collector.baseurl: https://github.com
    spring.profiles.active: GIT
    RUNNABLE_JAR: '/drone/src/argos-collector-service/target/argos-collector-service.jar'
  depends_on:
  - pitest
  - sonar

- name: regression test
  image: argosnotary/argos-build:latest
  commands:
  - cd argos-collector-test
  - mvn -q clean verify -Pregression-test-drone
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  depends_on:
  - argos-xldeploy-collector-service
  - argos-git-collector-service
  - argos-collector-xl-deploy-stub

- name: release argos collector service stub image
  image: plugins/docker
  settings:
    context: argos-collector-docker
    dockerfile: argos-collector-docker/ArgosCollectorDockerFile
    password:
      from_secret: docker_login_token
    repo: argosnotary/argos-collector-service
    tags:
    - ${DRONE_BRANCH//\//_}-beta
    username:
      from_secret: docker_login_user
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/*"
    event:
    - push
  depends_on:
  - regression test

- name: release argos collector service image
  image: plugins/docker
  settings:
    context: argos-collector-docker
    dockerfile: argos-collector-docker/ArgosCollectorDockerFile
    password:
      from_secret: docker_login_token
    repo: argosnotary/argos-collector-service
    tags:
    - ${DRONE_TAG}
    username:
      from_secret: docker_login_user
  when:
    event:
    - tag
  depends_on:
  - regression test

- name: sign artifacts
  image: plugins/gpgsign
  settings:
    detach_sign: true
    files:
    - argos-collector-service/target/*.jar
    - argos-collector-service/target/pom.xml
    key:
      from_secret: argos-signing-private-key
    passphrase:
      from_secret: argos-signing-private-key-passphrase
  when:
    event:
    - tag
  depends_on:
  - regression test

- name: deploy release to sonatype
  image: argosnotary/argos-build:latest
  commands:
  - mvn -q -f argos-collector-service/pom.xml deploy:deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/
  environment:
    ossrh_password:
      from_secret: ossrh_login_password
    ossrh_username:
      from_secret: ossrh_login_user
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  when:
    event:
    - tag
  depends_on:
  - sign artifacts

- name: slack on success
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  depends_on:
  - regression test
  - release argos collector service stub image
  - deploy release to sonatype
  - release argos collector service image
  
services:
- name: argos-collector-xl-deploy-stub
  image: argosnotary/xl-deploy-stub:2.25.1

volumes:
- name: mvn_cache
  temp: {}

---
kind: pipeline
type: docker
name: report result

platform:
  os: linux
  arch: amd64

steps:
- name: slack on failure
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

trigger:
  status:
  - failure

depends_on:
- argos-collector-build

...
